spring:
  r2dbc:
    host: localhost
    port: 3306
    db: solicitudes
    url: r2dbc:mysql://localhost:3306/solicitudes
    username: root
    password: 1234
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: DEBUG

jwt:
  secret: RCexi9khS2ZYXhEDL6oM8kQZp421HwF8CxGXgGHvrrw=